### ISSUE TITLE
Crash when installed on client only

### ISSUE THREAD

**Issue by kuba26038** [DragonsPlusMinecraft/VisualityReforged#2] opened 2022-11-19 13:07 UTC
[message(1).txt](https://github.com/ChannelingMC/visuality-forge/files/10047049/message.1.txt)

**Comment by RaymondBlaze** [comment] 2022-11-19 14:27
Seems to be duplicated with #1 
Again, I can't reproduce this crash in both develop and production environment with only Forge and the mod installed.
I need a smaller and simpler test environment to solve the problem, instead of being given some random 100+ mods to find the one to blame.

**Comment by RaymondBlaze** [comment] 2022-11-22 21:30
Visuality: Reforge-1.0-mc1.19+ has released, there're major changes in this update.
Though I still can't reproduce the crash, but maybe you'll want to try with the new version just in case it's fixed accidentally.

**Comment by Sandriell** [comment] 2022-11-26 03:42
I had this crash as well on 1.18.2.

So some background. I had spent a couple weeks play testing my modpack in single player with this mod installed and never once had a crash. However, within 15-30 minutes of playing on a dedicated server, with this mod only on the client and not the server, I experienced this same crash.

I updated to the 1.0 version, but also put the mod on the sever and have not had a crash since. So not sure if it was the update that fixed it or putting it on the server, but maybe something for you to explore. I know this is supposed to be an entirely client side mod, but maybe something is acting funny there.

Looking at both this issue and #1, both are also on dedicated servers too I believe.

**Comment by RaymondBlaze** [comment] 2022-11-28 10:39
> Looking at both this issue and #1, both are also on dedicated servers too I believe.

After testing on dedicated server, I find this could be caused by Forge's default behavior of forcibly syncing registries between server and client, causing any registry cannot be done only on client side.
This, however, is actually unfixable, its Forge's nature, and Visuality can't work without custom particles.
So, I'm gonna close this and claim the fact that Visuality: Reforge is not a client-side mod anymore.

**Closed as completed by RaymondBlaze** 2022-11-28 10:39 UTC
Labels: bug

**Comment by RaymondBlaze** [comment] 2023-04-22 12:27
Fixed in version 2.0 :)
